In [2]:
# General Utilites
import os
import numpy as np
import pandas as pd
import random
import yaml
import matplotlib
from matplotlib import pyplot as plt
import matplotlib.image as mpimg
%matplotlib inline
matplotlib.rcParams['figure.figsize'] = [20, 20]
from PIL import Image
from shutil import copyfile
import shutil
from IPython.display import clear_output

In [4]:
with open("create_scoring_df.yaml", "r") as input_stream: ### set input files
    settings = yaml.load(input_stream, Loader=yaml.FullLoader)
input_dir = f'{settings["input_dir"]}'
df_output_dir = f'{settings["df_output_dir"]}'

In [6]:
scoring_df = pd.DataFrame({"Filename" : os.listdir(input_dir)})
def get_filepath(row):
    return f"{input_dir}/{row['Filename']}"
scoring_df["Filepath"] = scoring_df.apply(lambda row: get_filepath(row), axis=1)
scoring_df.head(10)

               Filename                                           Filepath
0      CONN00118770.jpg  /gpfs/project/dollar/ajj38/shared/outliers/CON...
1        NHA-659466.jpg  /gpfs/project/dollar/ajj38/shared/outliers/NHA...
2  barcode-00525812.jpg  /gpfs/project/dollar/ajj38/shared/outliers/bar...
3        KIRI-04831.jpg  /gpfs/project/dollar/ajj38/shared/outliers/KIR...
4  barcode-00617175.jpg  /gpfs/project/dollar/ajj38/shared/outliers/bar...
5        NHA-551578.jpg  /gpfs/project/dollar/ajj38/shared/outliers/NHA...
6  barcode-00687644.jpg  /gpfs/project/dollar/ajj38/shared/outliers/bar...
7      CONN00174053.jpg  /gpfs/project/dollar/ajj38/shared/outliers/CON...
8           1910130.jpg  /gpfs/project/dollar/ajj38/shared/outliers/191...
9  barcode-01040685.jpg  /gpfs/project/dollar/ajj38/shared/outliers/bar...

In [7]:
status_list = ["Reproductive", "Flowering", "Fruiting", "Budding"]

for status in status_list:
    scoring_df.loc[:,f"{status} Status"] = float("NaN")

print(f"Total Number of imageS: {len(scoring_df)}")


scoring_df.loc[:,"Scored"] = False

Total Number of imageS: 679

In [8]:
scoring_df.head(10)

,Filename,Filepath,Reproductive Status,Flowering Status,Fruiting Status,Budding Status,Scored
0,CONN00118770.jpg,/gpfs/project/dollar/ajj38/shared/outliers/CON...,NaN,NaN,NaN,NaN,False
1,NHA-659466.jpg,/gpfs/project/dollar/ajj38/shared/outliers/NHA...,NaN,NaN,NaN,NaN,False
2,barcode-00525812.jpg,/gpfs/project/dollar/ajj38/shared/outliers/bar...,NaN,NaN,NaN,NaN,False
3,KIRI-04831.jpg,/gpfs/project/dollar/ajj38/shared/outliers/KIR...,NaN,NaN,NaN,NaN,False
4,barcode-00617175.jpg,/gpfs/project/dollar/ajj38/shared/outliers/bar...,NaN,NaN,NaN,NaN,False
5,NHA-551578.jpg,/gpfs/project/dollar/ajj38/shared/outliers/NHA...,NaN,NaN,NaN,NaN,False
6,barcode-00687644.jpg,/gpfs/project/dollar/ajj38/shared/outliers/bar...,NaN,NaN,NaN,NaN,False
7,CONN00174053.jpg,/gpfs/project/dollar/ajj38/shared/outliers/CON...,NaN,NaN,NaN,NaN,False
8,1910130.jpg,/gpfs/project/dollar/ajj38/shared/outliers/191...,NaN,NaN,NaN,NaN,False
9,barcode-01040685.jpg,/gpfs/project/dollar/ajj38/shared/outliers/bar...,NaN,NaN,NaN,NaN,False

In [9]:

scoring_df.to_csv(df_output_path)